import styles from './title.module.css';
import Image from 'next/image';
import img from "../../public/image/photo_2024-03-14_19-02-31 1.png";
export default function Title(){
return(<div className={styles.container} id='home'>
<div className={styles.textContainer}>
    
    <h1 className={styles.title}>Hi! I'm a Full Stack developer!</h1>
    <p className={styles.text}>My mission is to help you develop your website.</p>
</div>
<div className={styles.photoContainer}>
    <Image src={img} alt="my photo" width={518} height={595} priority loading="eager" className={styles.img}/> 
    <div  className={styles.caption} >this photo is generated by AI</div> 
</div>
</ div>)

}